// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ptlk.AlarmLogger.Data;

#nullable disable

namespace Ptlk.AlarmLogger.Data.HistoryMigrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20260622100721_AddAckCategoryFields")]
    partial class AddAckCategoryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alarm_logger")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ptlk.AlarmLogger.Models.AlarmHistoryRecord", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryTag")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("category_tag");

                    b.Property<bool>("ConditionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("condition_active");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("condition_name");

                    b.Property<string>("ConditionSubName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("condition_sub_name");

                    b.Property<bool>("EnableAck")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enable_ack");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time");

                    b.Property<bool>("IsAcknowledge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledge");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message");

                    b.Property<bool>("NeedAck")
                        .HasColumnType("boolean")
                        .HasColumnName("need_ack");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value_json");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value_json");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("quality");

                    b.Property<DateTimeOffset>("QualityTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quality_time");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_name");

                    b.HasKey("Timestamp", "Id")
                        .HasName("pk_alarm_history_records");

                    b.HasIndex("CategoryTag")
                        .HasDatabaseName("ix_alarm_history_records_category_tag");

                    b.HasIndex("ConditionActive")
                        .HasDatabaseName("ix_alarm_history_records_condition_active");

                    b.HasIndex("IsAcknowledge")
                        .HasDatabaseName("ix_alarm_history_records_is_acknowledge");

                    b.HasIndex("NeedAck")
                        .HasDatabaseName("ix_alarm_history_records_need_ack");

                    b.HasIndex("Quality")
                        .HasDatabaseName("ix_alarm_history_records_quality");

                    b.HasIndex("SourceName")
                        .HasDatabaseName("ix_alarm_history_records_source_name");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_alarm_history_records_timestamp");

                    b.HasIndex("SourceName", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_alarm_history_records_source_name_timestamp");

                    b.ToTable("alarm_history_records", "alarm_logger");
                });
#pragma warning restore 612, 618
        }
    }
}
